apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-client
  namespace: demos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-client
  template:
    metadata:
      labels:
        app: tcp-client
    spec:
      # Force to specific node
      # nodeName: aks-nodepool1-36018113-vmss000000
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: $registry_name/tcp-network-tester-client:$image_tag
          imagePullPolicy: Always
          name: tcp-client
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1500Mi
          env:
            - name: SERVER
              # value: "10.4.0.4"
              # value: "$vm_public_ip_address"
              # value: "$lb_public_ip_address"
              # value: "$vm_private_ip_address"
              value: "$server_address"
              # value: "$server_address_internal"
              # value: "$server_pod_ip_address"
            - name: PORT
              value: "10000"
            - name: INTERVAL
              value: "15"
            - name: CLIENTCOUNT
              value: "10000"
