apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server-stats-deployment
  namespace: demos
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: tcp-server-stats
  template:
    metadata:
      labels:
        app: tcp-server-stats
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - image: $registry_name/tcp-network-tester-server-stats:$image_tag
          imagePullPolicy: Always
          name: tcp-server-stats
          resources:
            requests:
              cpu: 1000m
              memory: 200Mi
            limits:
              cpu: 2000m
              memory: 1000Mi
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
