apiVersion: v1
kind: Service
metadata:
  name: tcp-server-internal-svc
  namespace: demos
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 10000
  selector:
    app: tcp-server
