apiVersion: v1
kind: Service
metadata:
  name: tcp-server-svc
  namespace: demos
spec:
  type: LoadBalancer
  ports:
    - port: 10000
  selector:
    app: tcp-server
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server-stats-svc
  namespace: demos
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: tcp-server-stats
